### ISSUE TITLE
About the extracted features

### ISSUE THREAD

**Issue by cpsxhao** [YehLi/xmodaler#14]
Hi, 

Thank you very much for your great code. May I ask if you would provide the extracted and pre-processed features (the .npz files) for datasets such as COCO, VCR, MSVTT?

Thank you very much!

**Comment by YehLi** [comment]
I have uploaded the msvd and msr-vtt features to the msvd_dataset/msrvtt_dataset folder (https://drive.google.com/drive/folders/1vx9n7tAIt8su0y_3tsPJGvMPBMm8JLCZ?usp=sharing).

For MSCOCO dataset,  please down the bottom up features from https://github.com/peteanderson80/bottom-up-attention and convert them into npz format with tools/create_feats.py.

**Comment by cpsxhao** [comment]
Hi, thanks very much for your help! BTW, may I ask where can I find the "mirror" features, or how can I convert the features in the bottom-up-attention repo into "mirror" npz-format features?

**Comment by YehLi** [comment]
The mirror features are extracted with the mirror images by https://github.com/peteanderson80/bottom-up-attention/blob/master/tools/generate_tsv.py.

**Comment by HanielF** [comment]
@YehLi Hi~ 
I notice that a video contains several frames and each frame can be used to extract up to 100 bboxes and roi features. Does the video npz-format features are assembled by concatting frames features？ 
The `generate_tsv.py` script only works for single image other than multiple frames.
