### ISSUE TITLE
Some errors caused by randomness in training

### ISSUE THREAD

**Issue by WangLanxiao** [YehLi/xmodaler#16]
Hello, I use my own data for image caption training in  4 GPUS num_workers=0. We found that most of the time, training and verification tests are normal. 

In rare cases, the following errors will be encounteredcWe suspect if some erros caused by the distribution makes the scoring process tags mismatch. 

Hope to get your reply.

Thanks so much.

![image](https://user-images.githubusercontent.com/34602362/131782480-cde496c9-4ba5-4726-ac91-35779b46f38d.png)

**Comment by jianjieluo** [comment]
hi @WangLanxiao ,

I have not encountered such errors. The error occurs in `coco-caption` evaluation package, you can try to check the content of `gts.keys()` and `res.keys()` to fix the bug. The error occurs probably in the construction process of your model predictions and your reference sentences file.

Best,
Jianjie

**Comment by jianjieluo** [comment]
Closed due to inactivity.
