### ISSUE TITLE
Flickr 30k feature

### ISSUE THREAD

**Issue by tgxs002** [YehLi/xmodaler#17]
Dear author,

I would like to know how to get the features needed for training retrieval model on Flickr 30k? I have downloaded the mdb features from [here](https://github.com/jiasenlu/vilbert_beta/tree/master/data), but how to convert them to npy/npz files?

Thanks!

**Comment by YehLi** [comment]
You can download the  Flickr 30k images and extract the features(tools/generate_npz.py) with npz format.
