### ISSUE TITLE
Captions on New Dataset

### ISSUE THREAD

**Issue by sramshetty** [YehLi/xmodaler#25]
I'm trying to get captions from a pre-trained model on a new dataset (crisismmd) and was wondering whether I need to extract the image features from the raw images first? It looks as though "kfg" utilizes features and their locations rather than raw images as I saw in "mscoco.py":
![image](https://user-images.githubusercontent.com/44125228/137046477-64c4ff82-dab4-4e43-87bd-1650f6811325.png)

Could I use a model like detectron2 to get these features, if that is what is needed? Or what would be the optimal way of doing this? Thank you in advance!

**Comment by YehLi** [comment]
You should use bottom-up-attention (https://github.com/peteanderson80/bottom-up-attention) to extract features and convert the tsv file into npz format (xmodaler/tools/create_feats.py) .

**Comment by jaycase1** [comment]
Excuse me，What does "tokens_ids" in the mscoco_caption_anno_train.pkl file mean and how did you get it?

**Comment by HanielF** [comment]
> You should use bottom-up-attention (https://github.com/peteanderson80/bottom-up-attention) to extract features and convert the tsv file into npz format (xmodaler/tools/create_feats.py) .

Are the features extracted by butd roi features? I'm a bit confused about whether this feature is roi feature or resnet152 feature.
