### ISSUE TITLE
G_TOKENS_IDS

### ISSUE THREAD

**Issue by sramshetty** [YehLi/xmodaler#27]
Hi,

I am trying to create a dataloader for a custom dataset and was able to build features using the bottum-up attention model. My current assumption is that G_TARGET_IDS are the token ids for the target text; however, I am unsure what G_TOKENS_IDS should be.

**Comment by dddavid4real** [comment]
Hi, may I ask how to generate the token ids during pre-processing? I didn't find this part in the tutorial. Thanks.

**Comment by sramshetty** [comment]
Sorry, it has been a while but maybe this response from the authors is what you are looking for: https://github.com/YehLi/xmodaler/issues/25#issuecomment-947430803. Hope that helps!
