### ISSUE TITLE
Predict on a given raw input

### ISSUE THREAD

**Issue by takuyara** [YehLi/xmodaler#3]
Dear contributors, is there a simple way I can directly predict results on my customized input? For example, in the video captioning, I want to generate the caption for my own video, which is in MP4 format. Is there a simple way to do it? Thanks.

**Comment by YehLi** [comment]
Thanks for your question, the current version mainly focuses on training. We will support it soon.

**Comment by DestoryVIP** [comment]
Me too....，I hope developers can provide a simple ways for prediction

**Comment by ithanwu** [comment]
> Thanks for your question, the current version mainly focuses on training. We will support it soon.

Then about half a year is passed , why no support update until now ?

**Comment by YehLi** [comment]
It supports the feature or raw image as input now. For raw image input,  please uncomment the line ''from .images.mscoco_raw import MSCoCoRawDataset'' in xmodaler/datasets/__init__.py. You can modify mscoco_raw.py to support other input format.

Please refer to configs/image_caption/transformer/clip_transformer_test.yaml or configs/image_caption/transformer/clip_transformer_test_raw.yaml for more detail.
