### ISSUE TITLE
[dataset] msvd pre-process error !

### ISSUE THREAD

**Issue by ithanwu** [YehLi/xmodaler#32]
Dear authors,
I used the script tools/msvd_preprocess.py to extract json ,but this error occurred ! 
the json is downloaded from this link 
https://drive.google.com/drive/folders/1-jvt6aKMDmhZC03DPEpwwgYxeL4PSD5J
so , it's strange that there's no "sentences" key !
Could you pls help me ? 
![image](https://user-images.githubusercontent.com/95072185/148324093-a99ff442-d0b8-4d6b-aa65-2dcd19ee1318.png)

**Comment by winnechan** [comment]
> 

Hi, the provided data files for msvd in the repo has been pre-processed already and no more operations are needed for training. The script tools/msvd_preprocess.py is utilized for the original dataset.json downloaded from the official website https://www.cs.utexas.edu/users/ml/clamp/videoDescription/#data

**Comment by YehLi** [comment]
dataset.json can be downloaded here (https://drive.google.com/file/d/1CDY2AIPlgS6MdHIYnanu_AFlmaXskB5M/view?usp=sharing)
