### ISSUE TITLE
The features of the provided msvd dataset are incomplete

### ISSUE THREAD

**Issue by HanielF** [YehLi/xmodaler#33]
MSVD dataset contains 1970 video clips, which is split into 1200(train set), 100(val set), 670(test set). 
While in what you provided in google drive, the number of video features and annnotations is only 1200 + 97 + 670, which misses 3 samples.

Moreover, the annotation of train set is not provided, and we cannot get the map of original video id to new video id, such as map `-4wsuPCjDBc_5_15` to '0'

**Comment by winnechan** [comment]
> 

Hi, the missing 3 samples are lost in the original dataset (i.e., the annotations are missing) and many published works only use 1967 videos for their experiments. 
The mappings between video names and the video ids can be derived from the dataset.json, which has been uploaded to the google drive.

**Comment by HanielF** [comment]
Thanks very much!
