### ISSUE TITLE
How to extract a global video feature based on butd?

### ISSUE THREAD

**Issue by HanielF** [YehLi/xmodaler#34]
I notice that butd output a 'npz' file corresponding to a single image.
When i want to extract video caption based on xmodaler, it requires a global video feature.

How to extract the final video feature from butd output of multi frames?

In MSRVTT dataset, I attempted to use topN objects which are voted by multi frames that extracted from a video uniformly. But captions of video is in poor quality. The BLUE of evaluate and test set only up to 0.6 and many `<UNK>` in captions.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/24732516/158177545-f2be910b-f98c-4df7-9b82-b558ed05134c.png">

**Comment by winnechan** [comment]
> 

Hi, if you only utilize the region-based features for objects in multi frames, you may lose the information of relationships among different objects, which would lead to poor performances from the models based on global video features.  

If you wound to derive the global video features from BUTD, you can first extract the global image features for multi frames from BUTD as this paper did (image-wise pooling of activations) https://www.cv-foundation.org/openaccess/content_cvpr_2016_workshops/w12/papers/Salvador_Faster_R-CNN_Features_CVPR_2016_paper.pdf, and then averagely pool them into global video features., which are, in turn, utilized to train your model.

**Comment by HanielF** [comment]
Thanks you very much~
