### ISSUE TITLE
使用自己的数据集产生的问题

### ISSUE THREAD

**Issue by saberforevery** [YehLi/xmodaler#36]
你好，我是一个新手，请问在使用自己的数据集时我该如何获取类似于mscoco_caption_anno_train.pkl的文件？在使用train_net.py时似乎想要这样的.pkl文件

**Comment by YehLi** [comment]
You can refer to https://github.com/YehLi/xmodaler/blob/master/tools/msvd_preprocess.py to generate the pkl files for your own dataset.

**Comment by saberforevery** [comment]
首先非常感谢您的回复，我还有另一个问题想请教，如果我想使用内置数据集mscoco进行训练，我应该选择哪一个数据集？当我使用[2014 Train/Val Image Features]，[2014 Testing Image Features (40K / 7.3GB)]和[2015 Testing Image Features (80K / 15GB)]时，总是会产生以下错误：[Errno 2] No such file or directory:./open_source_dataset/mscoco_dataset/features/up_down\\271789.npz'，是否是因为我选择了错误的数据集？

**Comment by saberforevery** [comment]
我似乎找到了问题产生的原因，这确实是由于数据集的内容不完整导致的，现在问题已经解决了。最后，再次感谢你的解答。

**Comment by santosh9sanjeev** [comment]
Can you pls let me know from where did you get the .npz files from?
It would be really helpful.
Thank you!

**Comment by 1301358882** [comment]
> 我似乎找到了问题产生的原因，这确实是由于数据集的内容不完整导致的，现在问题已经解决了。最后，再次感谢你的解答。

Hi, may I ask how it was solved?
Thank you very much.
