### ISSUE TITLE
Image to text search using clip

### ISSUE THREAD

**Issue by ltp1995** [YehLi/xmodaler#37]
Hi, dear author, in your latest CVPR2022 paper (Comprehending and Ordering Semantics for Image Captioning), how to retrieve semantically similar sentences for the input image using clip model, can you give some tutorials?
Thanks a lot!

**Comment by YehLi** [comment]
You can refer to the openai github (https://github.com/openai/CLIP) for more details.

**Comment by catfish132** [comment]
I see the vocabulary of the semantics label is in size of 907. Why is 907, and how can we get the word's meaning.

**Comment by YehLi** [comment]
The vocabulary can be obtaioned from https://github.com/s-gupta/visual-concepts/blob/master/vocabs/vocab_words.txt after removing some stopwords. We will upload the vocabulary later.

**Comment by YehLi** [comment]
The semantics label file is uploaded to configs/image_caption/cosnet/semantics labels.txt
