### ISSUE TITLE
Some questions about your CVPR 2022 paper

### ISSUE THREAD

**Issue by zml110120** [YehLi/xmodaler#38]
Dear author, 
         I have two questions about your latest CVPR2022 paper (Comprehending and Ordering Semantics for Image Captioning).
![image](https://user-images.githubusercontent.com/29172684/178029193-9ff4f4d9-6cd5-4502-be3c-19c1469b4e65.png)
         1.   What do you means about "slot" in the figure 2? And how did it works?
         2.   How can i get "Training Sentences" in Figure 2? wheather it is your own dataset or COCO dataset? Could you show me your 
              preprocess code?

**Comment by YehLi** [comment]
The slot is used to predict the missing semantics.
The training sentences is from COCO training set. The preprocess code will be uploaded later.
