### ISSUE TITLE
Exception: process 0 terminated with signal SIGSEGV

### ISSUE THREAD

**Issue by WangLanxiao** [YehLi/xmodaler#4]
hi
I try to train COCO caption for updown.yaml on 2080T
I meet Exception: process 0 terminated with signal SIGSEGV
thanks so much

**Comment by YehLi** [comment]
Can you share your training scripts?

**Comment by WangLanxiao** [comment]
Thank you very much for your reply, I have solved this problem. 
This is caused by the mismatch between the cuda version of the system and the cudatool under conda.

When using the code, I still have two confusions and hope to get a reply. 
①How to specify a model to test? I tried to look for eval.py but no found

②If the code is terminal during training, how to resume training?

Looking forward to your reply. 
Thank you very much for your contribution in the image caption.

**Comment by WangLanxiao** [comment]
I tried to use --resume and model.weight to reload the parameters of the model, but how to reload the optimizer state.

**Comment by jianjieluo** [comment]
hi @WangLanxiao ,

1. We integrated code for evaluation in `train_net.py`. To specify a model to test, you just need to use `MODEL.WEIGHTS` in your config file to specify a checkpoint file and then add `--eval-only` in your training script.

```
CUDA_VISIBLE_DEVICES=0 python3 train_net.py --num-gpus 1 --config-file ./configs/image_caption/updown/updown.yaml --eval-only
```

2. All you need to do to resume training is to add `--resume` in your original training script. The code will automatically find the last checkpoint in `OUTPUT_DIR` to resume training. Please noted that there should be a `last_checkpoint` file and the corresponding last `pth` model file in `OUTPUT_DIR`. In addition, the optimizer state is also stored in the `pth` model file and the code will automatically reload it if you use `--resume`. You can also refer [fvcore.common.checkpoint](https://github.com/facebookresearch/fvcore/blob/f10a1646bc74309e26641c75277e098e2d7900f6/fvcore/common/checkpoint.py#L196) for more details.

Best,
Jianjie

**Comment by WangLanxiao** [comment]
thanks so much!
