### ISSUE TITLE
Using different learning rates for different parameters

### ISSUE THREAD

**Issue by WangLanxiao** [YehLi/xmodaler#40]
Is it possible to set different parameter sets and different learning rates for the optimizer？

Such as :
       backbone_params = list(map(id,model.backbone.parameters()))  
       base_params = filter(lambda x:id(x) not in backbone_params ),model.parameters()) 
       optimizer = optim.Adam([  {'params': base_params },
                                                 {'params': model.backbone.parameters(), 'lr': 0.1*cfg.learning_rate}], lr=cfg.learning_rate)

If so, where should the changes be made?  And is there any other more direct way to achieve this requirement?

Thanks a lot. 
Waiting for your reply~

**Comment by YehLi** [comment]
You can modify get_default_optimizer_params in xmodaler\optim\build.py to achieve this requirement.
