### ISSUE TITLE
How to match video id and video name in provided MSVD data ? 

### ISSUE THREAD

**Issue by akira-l** [YehLi/xmodaler#41]
I found that the annotation JSON file for training is missing in provided data. 
How can I match the npy file in training to a particular video name? 
Could you please give me a matching dictionary?

**Comment by winnechan** [comment]
> I found that the annotation JSON file for training is missing in provided data. How can I match the npy file in training to a particular video name? Could you please give me a matching dictionary?

You can refer to this response https://github.com/YehLi/xmodaler/issues/33#issuecomment-1257926831 for the solution.
