### ISSUE TITLE
Downloading the model

### ISSUE THREAD

**Issue by atul1234anand** [YehLi/xmodaler#42]
Hi. The instructions to download the same seems a little difficult to understand. What do I do with the .rpm file that gets downloaded?

**Comment by YehLi** [comment]
You can set the WEIGHTS to the model path to load the parameters of the pre-trained model (e.g., the WEIGHTS in configs/image_caption/cosnet/cosnet_rl.yaml is set to '../models/cosnet/xe/cosnet_xe.pth')
