### ISSUE TITLE
Report errors when doing reinforcement learning

### ISSUE THREAD

**Issue by wangting0** [YehLi/xmodaler#45]
FileNotFoundError: [Errno 2] No such file or directory: '../open_source_dataset/mscoco_dataset/mscoco_train_cider.pkl'

**Comment by wangting0** [comment]
Resolved！

**Comment by YehLi** [comment]
The file can be downloaded from https://drive.google.com/drive/folders/16rCskpeG5ci02YiE8uR6P8AimV6WIkcB?usp=sharing

**Comment by wangting0** [comment]
OK.Thx！---- Replied Message ***@***.***>Date10/22/2022 01:58 ***@***.***> ***@***.***>,State ***@***.***>SubjectRe: [YehLi/xmodaler] Report errors when doing reinforcement learning (Issue #45)
The file can be downloaded from https://drive.google.com/drive/folders/16rCskpeG5ci02YiE8uR6P8AimV6WIkcB?usp=sharing

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/YehLi/xmodaler/issues/45#issuecomment-1287274716",
"url": "https://github.com/YehLi/xmodaler/issues/45#issuecomment-1287274716",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
