### ISSUE TITLE
使用COS-Cet时有几个.pkl文件找不到

### ISSUE THREAD

**Issue by Zhang122** [YehLi/xmodaler#58]
您好，在使用cosnet时，cosnet.yaml中提到的下面几个文件没有在您提供的Data preparation中找到，想问一下是怎么获取这几个文件的呢？
![~PYIAKA7GU(@TI}4ZR2@O6A](https://github.com/YehLi/xmodaler/assets/53432374/b2f93167-8995-4e35-bd42-9523b9f409c9)
![5W@{} MQHXOG5I9L$V G_{E](https://github.com/YehLi/xmodaler/assets/53432374/b8f4a750-3eb7-4bfe-81f7-acfb7fb5e19e)
![W2{0R}02II7BJB794DQPTXI](https://github.com/YehLi/xmodaler/assets/53432374/f36a7f68-a155-4121-9d40-12a7e21a6189)

**Comment by LeXueTao** [comment]
您好，请问您找到这几个文件了吗？
