### ISSUE TITLE
关于测试代码

### ISSUE THREAD

**Issue by pp-cv** [YehLi/xmodaler#6]
你所开源的库写的太好了，但是我有一个小问题就是你这里没有提供测试的代码吗

**Comment by YehLi** [comment]
We integrated code for evaluation in train_net.py. To specify a model to test, you just need to use MODEL.WEIGHTS in your config file to specify a checkpoint file and then add --eval-only in your training script.

CUDA_VISIBLE_DEVICES=0 python3 train_net.py --num-gpus 1 --config-file ./configs/image_caption/updown/updown.yaml --eval-only

**Comment by jianjieluo** [comment]
Closed due to inactivity.
